# Generated by Django 4.2 on 2023-04-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_manager', '0002_recipe_created_recipe_uploaded_recipe_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Day_of_week',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='category',
            new_name='Day_of_week',
        ),
    ]
